// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxrmutjkwxfwgwxlncpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4cm11dGprd3hmd2d3eGxuY3BjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyODExMDMsImV4cCI6MjA4NTg1NzEwM30.Y0LWwi6PmlloouJ3FybgA7vESHMWLHgCYToJ3H98tII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});