name: Generate Key Helper
on: workflow_dispatch # On le lance manuellement

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Key
        run: |
          keytool -genkey -v -keystore temp.jks -keyalg RSA -keysize 2048 -validity 10000 \
          -alias mucodec-alias -storepass MON_MOT_DE_PASSE -keypass MON_MOT_DE_PASSE \
          -dname "CN=Mucodec, OU=IT, O=Mucodec, L=Brazzaville, S=Congo, C=CG"
          
          echo "------ COPIEZ LE TEXTE CI-DESSOUS ------"
          base64 temp.jks
          echo "----------------------------------------"
